export const SEQUELIZE = 'SEQUELIZE';

export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

// Repository constants
export const CITY_REPOSITORY = 'CITY_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const PLANT_REPOSITORY = 'PLANT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_LOGIN_RECORD_REPOSITORY = 'USER_LOGIN_RECORD_REPOSITORY';
export const USER_PLATFORM_REPOSITORY = 'USER_PLATFORM_REPOSITORY';
export const USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY';
export const USER_SUBSCRIPTION_REPOSITORY = 'USER_SUBSCRIPTION_REPOSITORY';
export const USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY';
export const WATERING_RECORDS_REPOSITORY = 'WATERING_RECORDS_REPOSITORY';
export const FERTILIZER_RECORDS_REPOSITORY = 'FERTILIZER_RECORDS_REPOSITORY';

// Email template constants
export const WELCOME_TEMPLATE_KEY =
  '2d6f.1d8d8059f84364dd.k1.c79029d0-3513-11f0-9805-525400114fe6.196eb276ced';
export const CONFIRM_EMAIL_TEMPLATE_KEY = '';
export const FORGOT_PASS_TEMPLATE_KEY =
  '2d6f.1d8d8059f84364dd.k1.8ce008d0-3461-11f0-b52c-525400c09db6.196e69761dd';
export const PASSWORD_UPDATED_TEMPLATE_KEY =
  '2d6f.1d8d8059f84364dd.k1.fe69fe70-3515-11f0-9805-525400114fe6.196eb35efd7';
export const ACCOUNT_CLOSED_TEMPLATE_KEY = '';
export const NEWSLETTER_TEMPLATE_KEY = '';
