export const SEQUELIZE = 'SEQUELIZE';

export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const CITY_REPOSITORY = 'CITY_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const PLANT_REPOSITORY = 'PLANT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_LOGIN_RECORD_REPOSITORY = 'USER_LOGIN_RECORD_REPOSITORY';
export const USER_PLATFORM_REPOSITORY = 'USER_PLATFORM_REPOSITORY';
export const USER_ROLE_REPOSITORY = 'USER_ROLE_REPOSITORY';
export const USER_SUBSCRIPTION_REPOSITORY = 'USER_SUBSCRIPTION_REPOSITORY';
